# Generated by Django 2.2.7 on 2019-11-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindash', '0002_auto_20191114_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='cred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ipaddress', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
