# Generated by Django 2.2.7 on 2019-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindash', '0004_certalgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='document')),
            ],
        ),
    ]
