# Generated by Django 2.2.7 on 2020-02-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindash', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='passkey',
            field=models.CharField(default='A1B2C3D4E5', max_length=20),
        ),
    ]
