# Generated by Django 2.2.7 on 2020-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindash', '0006_id_passkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=50, unique=True)),
                ('connections', models.DecimalField(decimal_places=2, max_digits=4)),
                ('processes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vulnerability', models.IntegerField()),
                ('systemsec', models.IntegerField()),
            ],
        ),
    ]
