# Generated by Django 2.2.7 on 2020-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindash', '0007_devts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evalts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ipaddress', models.CharField(max_length=50, unique=True)),
                ('availability', models.IntegerField()),
                ('certificate', models.IntegerField()),
                ('retransmission', models.IntegerField()),
                ('delay', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trustscore', models.IntegerField()),
                ('eval_ipaddress', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
